### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 68: invalid continuation byte

### ISSUE THREAD

**Issue by freeskyd** [CaronLab/MhcVizPipe#11]
Dear developer team,
Thank you very much for this great software. When I test it，this message appears:

Traceback (most recent call last):
  File "D:\Software\MhcVizpipe-Pack\MhcVizPipe\python\lib\site-packages\MhcVizPipe\gui.py", line 1022, in run_analysis
    cl_tools.make_binding_predictions()
  File "D:\Software\MhcVizpipe-Pack\MhcVizPipe\python\lib\site-packages\MhcVizPipe\Tools\cl_tools.py", line 122, in make_binding_predictions
    predictions = netmhcpan.predict_dict()
  File "D:\Software\MhcVizpipe-Pack\MhcVizPipe\python\lib\site-packages\MhcVizPipe\Tools\netmhcpan_helper.py", line 325, in predict_dict
    self.make_predictions()
  File "D:\Software\MhcVizpipe-Pack\MhcVizPipe\python\lib\site-packages\MhcVizPipe\Tools\netmhcpan_helper.py", line 298, in make_predictions
    self._run_jobs()
  File "D:\Software\MhcVizpipe-Pack\MhcVizPipe\python\lib\site-packages\MhcVizPipe\Tools\netmhcpan_helper.py", line 225, in _run_jobs
    raise ChildProcessError(f'{job.stdout.decode()}\n\n{job.stderr.decode()}')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 68: invalid continuation byte

Thanks，

Best

Chao

**Comment by kevinkovalchik** [comment]
Hello,

It looks like Python isn't able to decode the console output from NetMHCpan. I haven't seen this before, but maybe it is happening because of the portable Python distribution we used. I have a couple questions to start:

1. What operating system are you using?
2. Are you using the standalone version of MhcVizPipe (i.e. you downloaded it from the release section of this repository) or did you install it into an existing Python using `pip install mhcvizpipe`?

Best,
Kevin

**Comment by wahlema** [comment]
Hello Kevin,

I get the same error message as described by Chao.
To answer your question, I use a windows operating system and installed MhcVizPipe following your step by step guide downloading and installing it from the release section of this repository (v0.7.9).

Best,
Maria
