### ISSUE TITLE
KeyError when running

### ISSUE THREAD

**Issue by courcelm** [CaronLab/MhcVizPipe#4]
I hoped yesterday it was related to missing jquery but it is not.

Traceback (most recent call last):
  File "/home/mathieu/MhcVizPipe/python/install/lib/python3.7/site-packages/MhcVizPipe/gui.py", line 1022, in run_analysis
    _ = analysis.make_report()
  File "/home/mathieu/MhcVizPipe/python/install/lib/python3.7/site-packages/MhcVizPipe/ReportTemplates/report.py", line 704, in make_report
    self.sample_overview_table(className='col-6')
  File "/home/mathieu/MhcVizPipe/python/install/lib/python3.7/site-packages/MhcVizPipe/ReportTemplates/report.py", line 147, in sample_overview_table
    within_length = self.peptide_numbers[sample.sample_name]['total']
KeyError: 'Test'

**Comment by courcelm** [comment]
I pasted sequences and clicked load data.

**Comment by kevinkovalchik** [comment]
That's new...
Not sure, I think the changes to the Popen call might have broken NetMHCpan as I parse the results from the stdout.

**Comment by kevinkovalchik** [comment]
I'll delete the changes on my side and see if it fixes it. So long as the paths to NetMHCpan etc in the config are absolute it shouldn't be necessary to access the environment path.

**Comment by courcelm** [comment]
I dit the same on my end.  I got a new error.

Traceback (most recent call last):
  File "/home/mathieu/MhcVizPipe/python/install/lib/python3.7/site-packages/MhcVizPipe/gui.py", line 1020, in run_analysis
    cl_tools.find_best_files()
  File "/home/mathieu/MhcVizPipe/python/install/lib/python3.7/site-packages/MhcVizPipe/Tools/cl_tools.py", line 208, in find_best_files
    with open(grouping/'images'/'gibbs.KLDvsClusters.tab', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/mhcvizpipe/2020-09-15_11:01:22.637595/gibbs/Test/unsupervised/4groups_12066/images/gibbs.KLDvsClusters.tab'

**Comment by kevinkovalchik** [comment]
Can you share your peptide list? The change is working on my side.

Also, see if there is an html file in `/tmp/mhcvizpipe/2020-09-15_11:01:22.637595/gibbs/Test/unsupervised/4groups_12066`. If not then something went wrong in gibbscluster.

**Comment by courcelm** [comment]
It was a single PEPTIDE . Large list is working fine.

**Comment by courcelm** [comment]
All looks good now!

**Comment by kevinkovalchik** [comment]
Great! I should add a check on how many peptides are uploaded. I do this before GibbsCluster runs on anything, but not upfront.
